import fs from 'node:fs';
import path from 'node:path';
import {siteOrigin,siteOutputDir} from './site-config.mjs';

const root = siteOutputDir;
const nav = [
  ['Homes', '/products/'],
  ['Why YOUTOME', '/about/'],
  ['Contact', '/contact/'],
];
const products = [
  {name:'Capsule One', category:'capsule', label:'CAPSULE SERIES', image:'/assets/capsule.webp', line:'A compact retreat with an unmistakable silhouette.', badge:'Compact living'},
  {name:'Capsule Panorama', category:'capsule', label:'CAPSULE SERIES', image:'/assets/capsule-panorama.webp', line:'Panoramic views meet a fully considered interior.', badge:'Panoramic design'},
  {name:'Capsule Grand', category:'capsule', label:'CAPSULE SERIES', image:'/assets/capsule-grand.webp', line:'More room to unwind, framed by the landscape.', badge:'Spacious design'},
  {name:'Apple Studio', category:'apple', label:'APPLE CABIN', image:'/assets/apple-cabin.webp', line:'An elegant footprint for stays, studios and escapes.', badge:'Versatile footprint'},
  {name:'Apple Living', category:'apple', label:'APPLE CABIN', image:'/assets/apple-living.webp', line:'A complete living space with room to feel at home.', badge:'Room to unwind'},
  {name:'Expandable One', category:'expandable', label:'EXPANDABLE SERIES', image:'/assets/expandable-one.webp', line:'Flexible space designed for efficient transport.', badge:'Flexible layout'},
];
const slug = name => name.toLowerCase().replaceAll(' ','-');
const arrow = '<span aria-hidden="true">↗</span>';
const icon = `<svg viewBox="0 0 44 44" fill="none" aria-hidden="true"><path d="M4 27 22 8l18 19M9 24v12h26V24" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M17 36V25h10v11" stroke="currentColor" stroke-width="2.5" stroke-linejoin="round"/></svg>`;

function header(active='') { return `<header class="site-header" id="top"><div class="nav-shell"><a class="brand" href="/" aria-label="YOUTOME home"><span class="brand-mark">${icon}</span><span>YOUTOME<small>BFC CHINA · 百福中国</small></span></a><nav class="desktop-nav" aria-label="Main navigation">${nav.map(([label,href])=>`<a href="${href}" ${active===href?'aria-current="page"':''}>${label}</a>`).join('')}</nav><a class="nav-cta" href="/contact/">Plan a project ${arrow}</a><button class="menu-toggle" aria-label="Open menu" aria-expanded="false" aria-controls="mobile-menu"><span></span><span></span></button></div><nav class="mobile-nav" id="mobile-menu" aria-label="Mobile navigation" hidden>${nav.map(([label,href])=>`<a href="${href}">${label}</a>`).join('')}<a href="/contact/">Plan a project</a></nav></header>`; }
function footer() { return `<footer class="footer"><div class="footer-top"><div><a class="brand brand-footer" href="/"><span class="brand-mark">${icon}</span><span>YOUTOME<small>BFC CHINA · 百福中国</small></span></a><p>Thoughtful prefab spaces for remarkable places.</p></div><div><span class="footer-title">Explore</span><a href="/products/">All homes</a><a href="/about/">About us</a><a href="/contact/">Contact</a></div><div><span class="footer-title">Collections</span><a href="/products/#capsule">Capsule houses</a><a href="/products/#apple">Apple cabins</a><a href="/products/#expandable">Expandable houses</a></div><div><span class="footer-title">Talk to us</span><a href="/contact/">Project enquiry ${arrow}</a><span>Contact details coming soon</span><span>A brand of BFC China</span></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} YOUTOME · A BFC China (百福中国) brand. All rights reserved.</span><span>Designed for living. Built to move.</span></div></footer>`; }
function page({title,description,active='',body,url='/'}) {
  const socialImage=products.find(product=>`/products/${slug(product.name)}/`===url)?.image ?? '/assets/hero.webp';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#101c1d"><title>${title}</title><meta name="description" content="${description}"><meta property="og:type" content="website"><meta property="og:site_name" content="YOUTOME"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:image" content="${siteOrigin}${socialImage}"><meta name="twitter:card" content="summary_large_image"><link rel="canonical" href="${siteOrigin}${url}"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="stylesheet" href="/styles.css"><script src="/app.js" defer></script></head><body>${header(active)}<main>${body}</main>${footer()}</body></html>`;
}
function productCard(p) { return `<article class="product-card" data-category="${p.category}"><a class="product-image" href="/products/${slug(p.name)}/"><img src="${p.image}" alt="Concept visualization of ${p.name} prefab home" loading="lazy" width="768" height="512"><span class="image-tag">${p.badge}</span></a><div class="product-body"><p class="eyebrow">${p.label}</p><div class="product-row"><h3>${p.name}</h3><a class="circle-link" href="/products/${slug(p.name)}/" aria-label="Explore ${p.name}">${arrow}</a></div><p>${p.line}</p></div></article>`; }

const home = page({title:'YOUTOME | Prefab Homes for Extraordinary Places',description:'Discover design-led capsule houses, cabins and expandable prefab homes by YOUTOME, a BFC China brand.',url:'/',body:`
<section class="hero"><img class="hero-image" src="/assets/hero.webp" alt="Contemporary prefab cabin beside a mountain lake at dusk" width="1536" height="1024" fetchpriority="high"><div class="hero-shade"></div><div class="hero-content container"><p class="eyebrow light"><span class="line"></span> MODULAR LIVING, REIMAGINED</p><h1>Spaces to stay.<br><em>Places to remember.</em></h1><p class="hero-copy">Architectural prefab homes designed to elevate hospitality, simplify development and bring people closer to nature.</p><div class="hero-actions"><a class="button button-light" href="/products/">Explore the collection ${arrow}</a><a class="text-link light-link" href="/contact/">Plan your project <span aria-hidden="true">→</span></a></div></div><div class="hero-bottom container"><span>01 / 03 · BUILT FOR THE WAY YOU LIVE</span><a href="#collections" aria-label="Scroll to collections">SCROLL TO EXPLORE <span aria-hidden="true">↓</span></a></div></section>
<section class="trust-bar"><div class="container trust-inner"><p>ONE PARTNER, FROM IDEA TO ARRIVAL</p><span>Design-led products</span><span>Factory-built quality</span><span>Global project support</span></div></section>
<section class="section collection-section container" id="collections"><div class="section-head"><div><p class="eyebrow">THE COLLECTIONS</p><h2>A home for every <em>possibility.</em></h2></div><p>From memorable guest stays to flexible personal space, choose the form that fits your landscape and your ambition.</p></div><div class="collection-grid"><a class="collection-card collection-large" href="/products/#capsule"><img src="/assets/capsule.webp" alt="Capsule house with panoramic glazing" loading="lazy" width="1536" height="1024"><span class="collection-overlay"><span>01 / CAPSULE HOUSES</span><strong>Make an impression.</strong><span class="collection-arrow">↗</span></span></a><a class="collection-card" href="/products/#apple"><img src="/assets/apple-cabin.webp" alt="Apple cabin in a green landscape" loading="lazy" width="1536" height="1024"><span class="collection-overlay"><span>02 / APPLE CABINS</span><strong>Feel at home.</strong><span class="collection-arrow">↗</span></span></a><a class="collection-card" href="/products/#expandable"><img src="/assets/hero.webp" alt="Modular cabin in a mountain setting" loading="lazy" width="1536" height="1024"><span class="collection-overlay"><span>03 / EXPANDABLE HOMES</span><strong>Make room for more.</strong><span class="collection-arrow">↗</span></span></a></div></section>
<section class="statement"><div class="container statement-grid"><p class="eyebrow light">BUILT WITH PURPOSE</p><div><h2>Better places begin with <em>better thinking.</em></h2><p>Our prefabricated approach brings design, structure and interior details together early in the process. The result: a considered space with a more predictable path from vision to reality.</p><a class="button button-outline" href="/about/">Meet YOUTOME ${arrow}</a></div></div></section>
<section class="section container"><div class="section-head product-head"><div><p class="eyebrow">SELECTED HOMES</p><h2>Designed to be <em>desired.</em></h2></div><a class="text-link" href="/products/">View all homes <span aria-hidden="true">→</span></a></div><div class="product-grid">${[products[1],products[4],products[5]].map(productCard).join('')}</div></section>
<section class="editorial"><div class="editorial-image"><img src="/assets/apple-cabin.webp" alt="Contemporary prefab cabin in a natural setting" loading="lazy" width="1536" height="1024"></div><div class="editorial-copy"><p class="eyebrow">FOR THE PLACES PEOPLE SEEK OUT</p><h2>Turn an empty site into a <em>destination.</em></h2><p>Create guest accommodation, a backyard retreat or a quiet place to work with a collection made for modern life.</p><ul><li><span>01</span> Hospitality & resorts</li><li><span>02</span> Rental properties</li><li><span>03</span> Personal living</li></ul><a class="button button-dark" href="/contact/">Discuss your project ${arrow}</a></div></section>
<section class="section process container"><div class="section-head"><div><p class="eyebrow">A CLEARER WAY FORWARD</p><h2>From first idea to <em>final placement.</em></h2></div></div><div class="steps"><div><span>01</span><h3>Share your vision</h3><p>Tell us where, how and why you plan to use your new space.</p></div><div><span>02</span><h3>Shape the right solution</h3><p>Explore models, layouts and options that match your project.</p></div><div><span>03</span><h3>Prepare with confidence</h3><p>Coordinate production, site preparation, delivery and installation.</p></div></div></section>
<section class="cta-band"><div class="container"><p class="eyebrow light">LET'S BUILD WHAT'S NEXT</p><h2>Where could your next space take you?</h2><a class="button button-light" href="/contact/">Start a conversation ${arrow}</a></div></section>`});

const productsPage = page({title:'Prefab Homes & Modular Cabins | YOUTOME',description:'Explore YOUTOME capsule houses, apple cabins and expandable prefab homes. Find the right modular home for hospitality, rentals or personal living.',active:'/products/',url:'/products/',body:`<section class="interior-hero products-hero"><div class="container"><p class="eyebrow light">OUR COLLECTION</p><h1>Thoughtful spaces.<br><em>Endless settings.</em></h1><p>Explore modular homes designed for distinctive stays and everyday possibility.</p></div></section><section class="section container products-section"><div class="catalog-intro"><div><p class="eyebrow">DISCOVER THE RANGE</p><h2>Find your fit.</h2></div><p>Browse by collection. Every project is different, and our team can help you decide which model suits your site, use and delivery needs.</p></div><div class="filters" role="group" aria-label="Filter homes"><button class="filter active" data-filter="all" aria-pressed="true">All homes</button><button class="filter" data-filter="capsule" aria-pressed="false">Capsule houses</button><button class="filter" data-filter="apple" aria-pressed="false">Apple cabins</button><button class="filter" data-filter="expandable" aria-pressed="false">Expandable homes</button></div><div class="product-grid catalog-grid">${products.map(productCard).join('')}</div><p class="catalog-note">Images are design visualizations; final details are confirmed per project. Looking for a different layout or finish? <a href="/contact/">Tell us about your project →</a></p></section><section class="cta-band"><div class="container"><p class="eyebrow light">PERSONAL PROJECT SUPPORT</p><h2>Find the model that feels right.</h2><a class="button button-light" href="/contact/">Plan your project ${arrow}</a></div></section>`});

const aboutPage = page({title:'About YOUTOME | Design-led Prefab Living',description:'Learn how YOUTOME combines design-led modular homes, modular design and project support for hospitality and personal living.',active:'/about/',url:'/about/',body:`<section class="interior-hero about-hero"><div class="container"><p class="eyebrow light">ABOUT YOUTOME</p><h1>Made to move.<br><em>Made to matter.</em></h1><p>We believe remarkable spaces should be easier to imagine, create and enjoy.</p></div></section><section class="section container about-intro"><div><p class="eyebrow">OUR APPROACH</p><h2>Architecture with a <em>practical edge.</em></h2></div><div><p>YOUTOME, a brand of BFC China (百福中国), is creating design-led prefabricated living solutions for residential, commercial and hospitality projects. Our collection brings memorable architecture together with carefully considered spaces.</p><p>From a single backyard cabin to a resort destination, we help match the right model to the right place, then support the path through specification, production and delivery.</p></div></section><section class="about-values container"><div><span>01 / DESIGN</span><h3>Spaces people remember</h3><p>Distinctive forms, generous glazing and interiors designed around the way people actually live.</p></div><div><span>02 / CRAFT</span><h3>Made with care</h3><p>A coordinated off-site approach brings structure, finishes and systems together with greater consistency.</p></div><div><span>03 / PARTNERSHIP</span><h3>Built around your project</h3><p>We help you understand model choices, preparation, shipping and placement before you commit.</p></div></section><section class="editorial about-editorial"><div class="editorial-image"><img src="/assets/hero.webp" alt="Modern modular cabin in a lakeside landscape" loading="lazy" width="1536" height="1024"></div><div class="editorial-copy"><p class="eyebrow">SEE IT FOR YOURSELF</p><h2>Explore the details up close.</h2><p>Explore forms, layouts and finishes with our team. We will help shape a configuration around your site, your guests and the experience you want to create.</p><a class="button button-dark" href="/contact/">Arrange a conversation ${arrow}</a></div></section><section class="cta-band"><div class="container"><p class="eyebrow light">YOUR NEXT PROJECT STARTS HERE</p><h2>Let's create a place worth arriving at.</h2><a class="button button-light" href="/contact/">Talk to our team ${arrow}</a></div></section>`});

const contactPage = page({title:'Contact YOUTOME | Plan Your Prefab Home',description:'Tell YOUTOME about your prefab home project. Ask about capsule houses, apple cabins, expandable homes, specifications and delivery.',active:'/contact/',url:'/contact/',body:`<section class="interior-hero contact-hero"><div class="container"><p class="eyebrow light">LET'S TALK</p><h1>Start with a place.<br><em>We'll shape the space.</em></h1><p>Share a little about your project and we'll help you find a considered way forward.</p></div></section><section class="section container contact-layout"><div class="contact-info"><p class="eyebrow">GET IN TOUCH</p><h2>We'd love to hear what you're imagining.</h2><p>Tell us your location, intended use and preferred model. The more context you share, the more useful our first conversation can be.</p><div class="contact-method"><span>CONTACT</span><p>Business email and messaging details will be added here.</p></div><div class="contact-method"><span>COMPANY</span><p>YOUTOME · A BFC China (百福中国) brand</p></div></div><form class="quote-form" id="quote-form"><p class="eyebrow">PROJECT ENQUIRY</p><h2>Tell us about your plan.</h2><div class="form-grid"><label>Your name <span>*</span><input name="name" type="text" autocomplete="name" required placeholder="Your name"></label><label>Email address <span>*</span><input name="email" type="email" autocomplete="email" required placeholder="you@example.com"></label><label>Country / region<input name="country" type="text" autocomplete="country-name" placeholder="Where is your project?"></label><label>Interested in<select name="model"><option value="">Select a collection</option><option>Capsule House</option><option>Apple Cabin</option><option>Expandable House</option><option>Not sure yet</option></select></label></div><label>Tell us about your project <span>*</span><textarea name="message" rows="5" required placeholder="Intended use, number of units, timeline or anything else we should know"></textarea></label><button class="button button-dark" type="submit">Copy enquiry details ${arrow}</button><p class="form-note">Contact details are being connected. For now, copy your project details and save them for our team.</p></form></section>`});

const projectGuide = `<section class="section container project-guide"><div class="section-head"><div><p class="eyebrow">A BETTER START</p><h2>What helps us plan <em>your project.</em></h2></div><p>A few practical details make the first conversation more useful. You can share them now or prepare them before reaching out.</p></div><div class="guide-grid"><article><span>01</span><h3>Location & climate</h3><p>Where will the home go, and will it be used year-round or seasonally?</p></article><article><span>02</span><h3>Use & quantity</h3><p>Is this for a resort, rental, business or private living? How many units are planned?</p></article><article><span>03</span><h3>Site readiness</h3><p>Consider vehicle access, ground conditions, utilities and any local approvals.</p></article><article><span>04</span><h3>Timing & scope</h3><p>Share your target schedule and which finishes or fittings matter most.</p></article></div><p class="guide-note">Final specifications, site requirements and delivery terms are confirmed in a written proposal for each project.</p></section>`;
const detailPages = products.map(p => {
  const url = `/products/${slug(p.name)}/`;
  const use = p.category === 'capsule' ? 'resort stays and distinctive rentals' : p.category === 'apple' ? 'private retreats and guest accommodation' : 'flexible residential and hospitality projects';
  const body = `<section class="detail-hero"><img src="${p.image}" alt="Concept visualization of ${p.name}" width="1536" height="1024" fetchpriority="high"><div class="detail-shade"></div><div class="container detail-hero-content"><a class="back-link" href="/products/">← All homes</a><p class="eyebrow light">${p.label}</p><h1>${p.name}</h1><p>${p.line}</p></div></section><section class="section container detail-layout"><div><p class="eyebrow">DESIGNED AROUND YOUR VISION</p><h2>A new perspective on <em>everyday space.</em></h2><p class="detail-copy">${p.name} brings the YOUTOME approach to ${use}. Its architectural form creates a memorable first impression, while a considered interior can be configured around your project needs.</p><a class="button button-dark" href="/contact/?model=${encodeURIComponent(p.name)}">Discuss this home ${arrow}</a></div><aside class="detail-aside"><span>THE COLLECTION</span><strong>${p.label}</strong><span>IDEAL FOR</span><strong>${use}</strong><span>CONFIGURATION</span><strong>Discuss options with our team</strong><small>Images are design visualizations. Final specifications, materials and availability are subject to confirmation.</small></aside></section>${projectGuide}<section class="section container related"><div class="section-head"><div><p class="eyebrow">EXPLORE MORE</p><h2>Other ways to <em>feel at home.</em></h2></div></div><div class="product-grid">${products.filter(x => x.name !== p.name).slice(0,3).map(productCard).join('')}</div></section><section class="cta-band"><div class="container"><p class="eyebrow light">LET'S SHAPE YOUR SPACE</p><h2>Ready to explore the possibilities?</h2><a class="button button-light" href="/contact/?model=${encodeURIComponent(p.name)}">Plan your project ${arrow}</a></div></section>`;
  return [`products/${slug(p.name)}/index.html`,page({title:`${p.name} | YOUTOME Prefab Homes`,description:`Explore ${p.name}, a YOUTOME prefab home concept for ${use}. See the design and discuss project options.`,active:'/products/',body,url})];
});
const contactPageWithGuide=contactPage.replace('</main>',`${projectGuide}</main>`);
const pages = [['index.html',home],['products/index.html',productsPage],['about/index.html',aboutPage],['contact/index.html',contactPageWithGuide],...detailPages];
for (const [file,contents] of pages) { const dest=path.join(root,file); fs.mkdirSync(path.dirname(dest),{recursive:true}); fs.writeFileSync(dest,contents); }
fs.writeFileSync(path.join(root,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${siteOrigin}/sitemap.xml\n`);
fs.writeFileSync(path.join(root,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+['/','/products/','/about/','/contact/',...products.map(p=>`/products/${slug(p.name)}/`)].map(url=>`<url><loc>${siteOrigin}${url}</loc></url>`).join('')+'</urlset>');
console.log(`Built ${pages.length} pages`);

