// Korean edition. Product names stay in their original form until the catalogue is finalized.
const ko = {
  "Homes":"주택","Why YOUTOME":"YOUTOME 소개","Contact":"문의","Plan a project":"프로젝트 상담","All homes":"모든 주택","About us":"회사 소개","Collections":"컬렉션","Explore":"살펴보기","Capsule houses":"캡슐 하우스","Apple cabins":"애플 캐빈","Expandable houses":"확장형 주택","Talk to us":"문의하기","Project enquiry":"프로젝트 문의","Contact details coming soon":"연락처가 곧 추가됩니다","A brand of BFC China":"BFC China의 브랜드","Thoughtful prefab spaces for remarkable places.":"특별한 장소를 위한 세심하게 설계된 조립식 공간.","Designed for living. Built to move.":"삶을 위해 설계하고, 이동을 고려해 만듭니다.","© 2026 YOUTOME · A BFC China (百福中国) brand. All rights reserved.":"© 2026 YOUTOME · BFC China (百福中国) 브랜드. 모든 권리 보유.",
  "MODULAR LIVING, REIMAGINED":"모듈형 생활의 새로운 해석","Spaces to stay.":"머물고 싶은 공간.","Places to remember.":"기억에 남는 장소.","Architectural prefab homes designed to elevate hospitality, simplify development and bring people closer to nature.":"숙박 경험을 높이고 개발 과정을 단순화하며 자연에 더 가까이 다가갈 수 있도록 설계한 조립식 주택입니다.","Explore the collection":"컬렉션 살펴보기","Plan your project":"프로젝트 상담하기","01 / 03 · BUILT FOR THE WAY YOU LIVE":"01 / 03 · 삶의 방식에 맞춘 공간","SCROLL TO EXPLORE":"아래로 내려 살펴보기","ONE PARTNER, FROM IDEA TO ARRIVAL":"아이디어부터 설치까지 함께하는 파트너","Design-led products":"디자인 중심 제품","Factory-built quality":"공장에서 관리하는 품질","Global project support":"해외 프로젝트 지원",
  "THE COLLECTIONS":"컬렉션","A home for every":"모든 가능성을 위한","possibility.":"하나의 집.","From memorable guest stays to flexible personal space, choose the form that fits your landscape and your ambition.":"기억에 남는 숙박 공간부터 유연한 개인 공간까지, 부지와 목표에 맞는 형태를 선택하세요.","01 / CAPSULE HOUSES":"01 / 캡슐 하우스","02 / APPLE CABINS":"02 / 애플 캐빈","03 / EXPANDABLE HOMES":"03 / 확장형 주택","Make an impression.":"인상적인 첫 만남.","Feel at home.":"집처럼 편안하게.","Make room for more.":"가능성을 넓히세요.",
  "BUILT WITH PURPOSE":"목적을 담은 디자인","Better places begin with":"더 나은 장소는","better thinking.":"더 깊은 생각에서 시작됩니다.","Our prefabricated approach brings design, structure and interior details together early in the process. The result: a considered space with a more predictable path from vision to reality.":"YOUTOME의 조립식 건축 방식은 초기 단계부터 디자인, 구조, 인테리어 요소를 함께 고려합니다. 이를 통해 구상부터 실현까지의 과정을 더 명확하게 계획할 수 있습니다.","Meet YOUTOME":"YOUTOME 알아보기","SELECTED HOMES":"추천 주택","Designed to be":"눈길을 사로잡도록","desired.":"설계했습니다.","View all homes":"모든 주택 보기","CAPSULE SERIES":"캡슐 시리즈","APPLE CABIN":"애플 캐빈","EXPANDABLE SERIES":"확장형 시리즈","Compact living":"아담한 생활 공간","Panoramic design":"파노라마 디자인","Spacious design":"넉넉한 공간 설계","Versatile footprint":"다양하게 쓰는 공간","Room to unwind":"여유로운 휴식 공간","Flexible layout":"유연한 평면 구성","A compact retreat with an unmistakable silhouette.":"개성 있는 외관을 갖춘 아담한 휴식 공간.","Panoramic views meet a fully considered interior.":"넓은 전망과 세심하게 계획한 실내 공간의 만남.","More room to unwind, framed by the landscape.":"풍경 속에서 더 여유롭게 쉬는 공간.","An elegant footprint for stays, studios and escapes.":"숙박, 작업실, 휴식처로 어울리는 우아한 공간.","A complete living space with room to feel at home.":"집처럼 편안하게 머물 수 있는 온전한 생활 공간.","Flexible space designed for efficient transport.":"효율적인 운송을 고려한 유연한 공간.",
  "FOR THE PLACES PEOPLE SEEK OUT":"사람들이 찾아오는 장소를 위해","Turn an empty site into a":"빈 부지를 특별한","destination.":"목적지로 바꾸세요.","Create guest accommodation, a backyard retreat or a quiet place to work with a collection made for modern life.":"현대적인 삶을 위한 컬렉션으로 숙박 시설, 정원의 휴식처 또는 조용한 업무 공간을 만들어 보세요.","Hospitality & resorts":"숙박 시설 및 리조트","Rental properties":"임대 숙소","Personal living":"개인 주거","Discuss your project":"프로젝트 상담하기","A CLEARER WAY FORWARD":"더 명확한 진행 과정","From first idea to":"첫 아이디어부터","final placement.":"최종 설치까지.","Share your vision":"구상을 알려주세요","Tell us where, how and why you plan to use your new space.":"새 공간을 어디에, 어떻게, 어떤 목적으로 사용할지 알려주세요.","Shape the right solution":"적합한 해법 찾기","Explore models, layouts and options that match your project.":"프로젝트에 맞는 모델, 평면, 선택 사항을 살펴보세요.","Prepare with confidence":"체계적으로 준비하기","Coordinate production, site preparation, delivery and installation.":"생산, 부지 준비, 배송, 설치 일정을 함께 조율합니다.","LET'S BUILD WHAT'S NEXT":"다음 프로젝트를 함께 시작하세요","Where could your next space take you?":"다음 공간은 어떤 가능성을 열어줄까요?","Start a conversation":"상담 시작하기",
  "OUR COLLECTION":"YOUTOME 컬렉션","Thoughtful spaces.":"세심하게 설계한 공간.","Endless settings.":"다양한 활용 가능성.","Explore modular homes designed for distinctive stays and everyday possibility.":"특별한 숙박 경험과 일상의 가능성을 위해 설계한 모듈형 주택을 살펴보세요.","DISCOVER THE RANGE":"제품군 살펴보기","Find your fit.":"내게 맞는 공간을 찾으세요.","Browse by collection. Every project is different, and our team can help you decide which model suits your site, use and delivery needs.":"컬렉션별로 살펴보세요. 프로젝트마다 조건이 다릅니다. YOUTOME 팀이 부지, 용도, 배송 요건에 맞는 모델 선택을 도와드립니다.","Expandable homes":"확장형 주택","Images are design visualizations; final details are confirmed per project. Looking for a different layout or finish?":"이미지는 디자인 시안입니다. 최종 세부 사항은 프로젝트별로 확정됩니다. 다른 평면이나 마감을 찾고 계신가요?","Tell us about your project →":"프로젝트 문의하기 →","PERSONAL PROJECT SUPPORT":"프로젝트 맞춤 지원","Find the model that feels right.":"잘 맞는 모델을 찾아보세요.",
  "ABOUT YOUTOME":"YOUTOME 소개","Made to move.":"변화에 맞춰 만들고.","Made to matter.":"의미 있는 공간을 만듭니다.","We believe remarkable spaces should be easier to imagine, create and enjoy.":"특별한 공간을 구상하고 만들고 누리는 일이 더 쉬워져야 한다고 믿습니다.","OUR APPROACH":"YOUTOME의 방식","Architecture with a":"아름다운 디자인과","practical edge.":"실용성을 함께.","YOUTOME, a brand of BFC China (百福中国), is creating design-led prefabricated living solutions for residential, commercial and hospitality projects. Our collection brings memorable architecture together with carefully considered spaces.":"BFC China (百福中国)의 브랜드인 YOUTOME는 주거, 상업, 숙박 프로젝트를 위한 디자인 중심의 조립식 공간을 만듭니다. 인상적인 건축 디자인과 세심하게 계획한 공간을 하나의 컬렉션으로 선보입니다.","From a single backyard cabin to a resort destination, we help match the right model to the right place, then support the path through specification, production and delivery.":"정원의 작은 캐빈부터 리조트까지, 장소에 맞는 모델을 함께 찾고 사양 확정, 생산, 배송 과정도 지원합니다.","01 / DESIGN":"01 / 디자인","02 / CRAFT":"02 / 제작","03 / PARTNERSHIP":"03 / 협력","Spaces people remember":"오래 기억되는 공간","Distinctive forms, generous glazing and interiors designed around the way people actually live.":"독특한 형태, 넓은 창, 실제 생활 방식을 고려한 인테리어를 갖춥니다.","Made with care":"세심한 제작","A coordinated off-site approach brings structure, finishes and systems together with greater consistency.":"공장에서 구조, 마감, 설비를 함께 조율해 일관된 품질을 추구합니다.","Built around your project":"프로젝트에 맞춘 지원","We help you understand model choices, preparation, shipping and placement before you commit.":"결정하기 전에 모델 선택, 부지 준비, 운송, 설치 과정을 이해할 수 있도록 돕습니다.","SEE IT FOR YOURSELF":"직접 살펴보세요","Explore the details up close.":"세부 사항까지 확인하세요.","Explore forms, layouts and finishes with our team. We will help shape a configuration around your site, your guests and the experience you want to create.":"YOUTOME 팀과 함께 형태, 평면, 마감재를 살펴보세요. 부지와 이용자, 원하는 경험에 맞는 구성을 함께 계획합니다.","Arrange a conversation":"상담 예약하기","YOUR NEXT PROJECT STARTS HERE":"다음 프로젝트는 여기서 시작됩니다","Let's create a place worth arriving at.":"찾아갈 가치가 있는 장소를 함께 만듭니다.","Talk to our team":"팀에 문의하기",
  "LET'S TALK":"함께 이야기해요","Start with a place.":"장소에서 시작해","We'll shape the space.":"공간을 함께 완성합니다.","Share a little about your project and we'll help you find a considered way forward.":"프로젝트에 대해 간단히 알려주시면 다음 단계를 함께 고민하겠습니다.","GET IN TOUCH":"문의하기","We'd love to hear what you're imagining.":"구상 중인 이야기를 들려주세요.","Tell us your location, intended use and preferred model. The more context you share, the more useful our first conversation can be.":"위치, 사용 목적, 관심 모델을 알려주세요. 정보가 구체적일수록 첫 상담에 도움이 됩니다.","CONTACT":"연락처","Business email and messaging details will be added here.":"업무용 이메일과 메시지 연락처가 이곳에 추가됩니다.","COMPANY":"회사","YOUTOME · A BFC China (百福中国) brand":"YOUTOME · BFC China (百福中国) 브랜드","PROJECT ENQUIRY":"프로젝트 문의","Tell us about your plan.":"계획을 알려주세요.","Your name":"이름","Email address":"이메일 주소","Country / region":"국가 / 지역","Interested in":"관심 제품","Select a collection":"컬렉션 선택","Capsule House":"캡슐 하우스","Apple Cabin":"애플 캐빈","Expandable House":"확장형 주택","Not sure yet":"아직 결정하지 않았어요","Tell us about your project":"프로젝트에 대해 알려주세요","Copy enquiry details":"문의 내용 복사","Contact details are being connected. For now, copy your project details and save them for our team.":"연락 채널을 준비 중입니다. 지금은 프로젝트 내용을 복사해 보관해 주세요.",
  "DESIGNED AROUND YOUR VISION":"구상에 맞춘 디자인","A new perspective on":"일상 공간을 바라보는","everyday space.":"새로운 시선.","Discuss this home":"이 주택 상담하기","THE COLLECTION":"컬렉션","IDEAL FOR":"추천 용도","CONFIGURATION":"구성","Discuss options with our team":"팀과 선택 사항 상담하기","Images are design visualizations. Final specifications, materials and availability are subject to confirmation.":"이미지는 디자인 시안입니다. 최종 사양, 자재, 공급 가능 여부는 확인 후 확정됩니다.","EXPLORE MORE":"더 살펴보기","Other ways to":"집처럼 편안하게","feel at home.":"머무는 다른 방법.","LET'S SHAPE YOUR SPACE":"공간을 함께 만들어 보세요","Ready to explore the possibilities?":"새로운 가능성을 살펴볼 준비가 되셨나요?","← All homes":"← 모든 주택","flexible residential and hospitality projects":"유연한 주거 및 숙박 프로젝트","private retreats and guest accommodation":"개인 휴식 공간 및 게스트 숙소","resort stays and distinctive rentals":"리조트 숙박 및 특별한 임대 숙소",
  "A BETTER START":"더 좋은 시작","What helps us plan":"프로젝트 계획에","your project.":"도움이 되는 정보.","A few practical details make the first conversation more useful. You can share them now or prepare them before reaching out.":"몇 가지 실무 정보를 준비하면 첫 상담이 더 유익해집니다. 지금 알려주시거나 연락하기 전에 정리해 두셔도 좋습니다.","Location & climate":"위치와 기후","Where will the home go, and will it be used year-round or seasonally?":"주택을 어디에 설치하며 연중 또는 계절별로 사용하나요?","Use & quantity":"용도와 수량","Is this for a resort, rental, business or private living? How many units are planned?":"리조트, 임대, 사업장, 개인 주거 중 어떤 용도인가요? 몇 채를 계획하고 있나요?","Site readiness":"부지 준비 상태","Consider vehicle access, ground conditions, utilities and any local approvals.":"차량 진입, 지반 상태, 기반 시설, 현지 인허가 사항을 고려하세요.","Timing & scope":"일정과 범위","Share your target schedule and which finishes or fittings matter most.":"희망 일정과 중요하게 생각하는 마감재 또는 설비를 알려주세요.","Final specifications, site requirements and delivery terms are confirmed in a written proposal for each project.":"최종 사양, 부지 요건, 배송 조건은 프로젝트별 서면 제안서에서 확정됩니다.",
  "Discover design-led capsule houses, cabins and expandable prefab homes by YOUTOME, a BFC China brand.":"BFC China 브랜드 YOUTOME의 디자인 중심 캡슐 하우스, 캐빈, 확장형 조립식 주택을 만나보세요.","Explore YOUTOME capsule houses, apple cabins and expandable prefab homes. Find the right modular home for hospitality, rentals or personal living.":"YOUTOME의 캡슐 하우스, 애플 캐빈, 확장형 주택을 살펴보세요. 숙박, 임대, 개인 주거에 맞는 모듈형 주택을 찾을 수 있습니다.","Learn how YOUTOME combines design-led modular homes, modular design and project support for hospitality and personal living.":"YOUTOME가 디자인 중심 모듈형 주택과 프로젝트 지원을 결합해 숙박 및 개인 주거 공간을 만드는 방식을 알아보세요.","Tell YOUTOME about your prefab home project. Ask about capsule houses, apple cabins, expandable homes, specifications and delivery.":"YOUTOME에 조립식 주택 프로젝트를 알려주세요. 캡슐 하우스, 애플 캐빈, 확장형 주택, 사양 및 배송에 관해 문의하실 수 있습니다.","Main navigation":"기본 메뉴","Mobile navigation":"모바일 메뉴","Open menu":"메뉴 열기","Scroll to collections":"컬렉션으로 이동","Filter homes":"주택 필터","Intended use, number of units, timeline or anything else we should know":"사용 목적, 수량, 일정 등 알려주실 내용","Where is your project?":"프로젝트 위치는 어디인가요?","YOUTOME home":"YOUTOME 홈페이지","Contemporary prefab cabin beside a mountain lake at dusk":"해 질 무렵 산속 호숫가에 놓인 현대적인 조립식 캐빈","Capsule house with panoramic glazing":"파노라마 창을 갖춘 캡슐 하우스","Apple cabin in a green landscape":"푸른 풍경 속 애플 캐빈","Modular cabin in a mountain setting":"산속 풍경의 모듈형 캐빈","Contemporary prefab cabin in a natural setting":"자연 속 현대적인 조립식 캐빈","Modern modular cabin in a lakeside landscape":"호숫가 풍경 속 현대적인 모듈형 캐빈"
};

for (const name of ['Capsule One','Capsule Panorama','Capsule Grand','Apple Studio','Apple Living','Expandable One']) {
  const audience = name.startsWith('Capsule') ? 'resort stays and distinctive rentals' : name.startsWith('Apple') ? 'private retreats and guest accommodation' : 'flexible residential and hospitality projects';
  ko[`${name} brings the YOUTOME approach to ${audience}. Its architectural form creates a memorable first impression, while a considered interior can be configured around your project needs.`] = `${name}: ${ko[audience]}에 어울리는 YOUTOME의 제안입니다. 인상적인 건축 형태와 프로젝트에 맞춰 구성할 수 있는 실내 공간을 갖췄습니다.`;
  ko[`${name} | YOUTOME Prefab Homes`] = `${name} | YOUTOME 조립식 주택`;
}
ko['YOUTOME | Prefab Homes for Extraordinary Places'] = 'YOUTOME | 특별한 장소를 위한 조립식 주택';
ko['Prefab Homes & Modular Cabins | YOUTOME'] = '조립식 주택과 모듈형 캐빈 | YOUTOME';
ko['About YOUTOME | Design-led Prefab Living'] = 'YOUTOME 소개 | 디자인 중심 조립식 주택';
ko['Contact YOUTOME | Plan Your Prefab Home'] = 'YOUTOME 문의 | 조립식 주택 프로젝트 상담';
export default ko;
