// Simplified Chinese edition for BFC China's home market and global buyers.
const zh={
  "Homes":"产品系列","Why YOUTOME":"为什么选择 YOUTOME","Contact":"联系我们","Plan a project":"规划项目","All homes":"全部产品","About us":"关于我们","Collections":"产品系列","Capsule houses":"太空舱","Apple cabins":"苹果舱","Expandable houses":"拓展式房屋","Talk to us":"与我们沟通","Project enquiry":"项目咨询","Contact details coming soon":"联系方式即将公布","A brand of BFC China":"百福中国旗下品牌","Thoughtful prefab spaces for remarkable places.":"为不凡目的地打造精心设计的预制空间。","Designed for living. Built to move.":"为生活而设计，为灵活而建造。","© 2026 YOUTOME · A BFC China (百福中国) brand. All rights reserved.":"© 2026 YOUTOME · 百福中国旗下品牌。保留所有权利。",
  "MODULAR LIVING, REIMAGINED":"重塑模块化生活","Spaces to stay.":"栖居于此。","Places to remember.":"铭记于心。","Architectural prefab homes designed to elevate hospitality, simplify development and bring people closer to nature.":"兼具建筑美感的预制房屋，让旅居体验更出色、项目推进更清晰，也让人与自然更亲近。","Explore the collection":"探索产品系列","Plan your project":"规划您的项目","01 / 03 · BUILT FOR THE WAY YOU LIVE":"01 / 03 · 为您的生活方式而造","SCROLL TO EXPLORE":"向下探索","ONE PARTNER, FROM IDEA TO ARRIVAL":"从构想到落地的一站式伙伴","Design-led products":"设计驱动的产品","Factory-built quality":"工厂制造品质","Global project support":"全球项目支持",
  "THE COLLECTIONS":"产品系列","A home for every":"每一种可能，","possibility.":"都有理想空间。","From memorable guest stays to flexible personal space, choose the form that fits your landscape and your ambition.":"从令人难忘的旅宿空间到灵活的私人场所，选择契合场地与愿景的产品形态。","01 / CAPSULE HOUSES":"01 / 太空舱","02 / APPLE CABINS":"02 / 苹果舱","03 / EXPANDABLE HOMES":"03 / 拓展式房屋","Make an impression.":"第一眼，就令人难忘。","Feel at home.":"自在，如在家中。","Make room for more.":"为更多可能留出空间。",
  "BUILT WITH PURPOSE":"设计有度，建造有据","Better places begin with":"更好的空间，始于","better thinking.":"更周全的思考。","Our prefabricated approach brings design, structure and interior details together early in the process. The result: a considered space with a more predictable path from vision to reality.":"我们的预制化方法在项目早期整合设计、结构与室内细节，让从构想到落地的路径更清晰、结果更可预期。","Meet YOUTOME":"了解 YOUTOME","SELECTED HOMES":"精选产品","Designed to be":"因设计，","desired.":"而令人向往。","View all homes":"查看全部产品",
  "CAPSULE SERIES":"太空舱系列","APPLE CABIN":"苹果舱","EXPANDABLE SERIES":"拓展式系列","Compact living":"紧凑型空间","Panoramic design":"全景设计","Spacious design":"宽敞布局","Versatile footprint":"灵活尺寸","Room to unwind":"舒展空间","Flexible layout":"灵活布局","A compact retreat with an unmistakable silhouette.":"以鲜明轮廓定义紧凑度假空间。","Panoramic views meet a fully considered interior.":"全景视野与精心规划的室内空间相遇。","More room to unwind, framed by the landscape.":"于自然景致中，享受更从容的休憩空间。","An elegant footprint for stays, studios and escapes.":"适合旅宿、工作室和私享度假的优雅空间。","A complete living space with room to feel at home.":"功能完整、自在如家的居住空间。","Flexible space designed for efficient transport.":"兼顾灵活使用与高效运输的空间方案。",
  "FOR THE PLACES PEOPLE SEEK OUT":"为令人向往的目的地而来","Turn an empty site into a":"让一片空地成为","destination.":"值得前往的目的地。","Create guest accommodation, a backyard retreat or a quiet place to work with a collection made for modern life.":"以面向现代生活的产品，打造旅宿客房、庭院休憩空间或安静的工作场所。","Hospitality & resorts":"酒店与度假区","Rental properties":"租赁物业","Personal living":"私人居住","Discuss your project":"讨论您的项目","A CLEARER WAY FORWARD":"更清晰的项目路径","From first idea to":"从最初构想","final placement.":"到最终落位。","Share your vision":"分享您的构想","Tell us where, how and why you plan to use your new space.":"告诉我们新空间的所在地、用途和使用方式。","Shape the right solution":"找到适合的方案","Explore models, layouts and options that match your project.":"探索契合项目的型号、布局和配置。","Prepare with confidence":"从容推进准备工作","Coordinate production, site preparation, delivery and installation.":"统筹生产、场地准备、运输与安装。","LET'S BUILD WHAT'S NEXT":"开启下一个项目","Where could your next space take you?":"您的下一处空间，将通往哪里？","Start a conversation":"开始沟通",
  "OUR COLLECTION":"产品系列","Thoughtful spaces.":"精心设计的空间。","Endless settings.":"多元场景的可能。","Explore modular homes designed for distinctive stays and everyday possibility.":"探索兼顾特色旅居与日常使用的模块化房屋。","DISCOVER THE RANGE":"探索产品","Find your fit.":"找到适合的选择。","Browse by collection. Every project is different, and our team can help you decide which model suits your site, use and delivery needs.":"按系列浏览产品。每个项目都有不同需求，我们可协助您根据场地、用途和运输条件选择合适的型号。","Expandable homes":"拓展式房屋","Images are design visualizations; final details are confirmed per project. Looking for a different layout or finish?":"图片为设计概念效果图；最终细节以具体项目确认为准。需要不同的布局或饰面？","Tell us about your project →":"告诉我们您的项目 →","PERSONAL PROJECT SUPPORT":"针对项目的专属支持","Find the model that feels right.":"找到恰如其分的产品。",
  "ABOUT YOUTOME":"关于 YOUTOME","Made to move.":"因灵活而生。","Made to matter.":"为价值而造。","We believe remarkable spaces should be easier to imagine, create and enjoy.":"我们相信，令人向往的空间应当更容易被构想、实现并享用。","OUR APPROACH":"我们的方法","Architecture with a":"建筑美感与","practical edge.":"实用思维并行。","YOUTOME, a brand of BFC China (百福中国), is creating design-led prefabricated living solutions for residential, commercial and hospitality projects. Our collection brings memorable architecture together with carefully considered spaces.":"YOUTOME 是百福中国旗下品牌，致力于为居住、商业和旅宿项目打造设计驱动的预制空间。我们的产品将鲜明的建筑语言与周全的空间规划结合。","From a single backyard cabin to a resort destination, we help match the right model to the right place, then support the path through specification, production and delivery.":"从庭院中的独立小屋到度假目的地，我们协助您为场地选择合适的产品，并在配置确认、生产和交付过程中提供支持。","01 / DESIGN":"01 / 设计","02 / CRAFT":"02 / 工艺","03 / PARTNERSHIP":"03 / 协作","Spaces people remember":"让人记住的空间","Distinctive forms, generous glazing and interiors designed around the way people actually live.":"鲜明的外观、大面积采光，以及贴合真实生活方式的室内设计。","Made with care":"用心把控细节","A coordinated off-site approach brings structure, finishes and systems together with greater consistency.":"有序的预制流程，让结构、饰面和设备系统实现更一致的整合。","Built around your project":"围绕项目而设计","We help you understand model choices, preparation, shipping and placement before you commit.":"在作出决定前，帮助您了解型号选择、场地准备、运输和落位要求。","SEE IT FOR YOURSELF":"深入了解产品","Explore the details up close.":"细节，值得细看。","Explore forms, layouts and finishes with our team. We will help shape a configuration around your site, your guests and the experience you want to create.":"与我们的团队一同探索外观、布局与饰面，围绕场地、客群及目标体验规划合适的配置。","Arrange a conversation":"预约沟通","YOUR NEXT PROJECT STARTS HERE":"下一个项目，从这里开始","Let's create a place worth arriving at.":"共同打造值得抵达的目的地。","Talk to our team":"与团队沟通",
  "LET'S TALK":"开启对话","Start with a place.":"从场地出发。","We'll shape the space.":"共同塑造空间。","Share a little about your project and we'll help you find a considered way forward.":"简要介绍您的项目，我们将协助您梳理下一步。","GET IN TOUCH":"联系我们","We'd love to hear what you're imagining.":"期待听到您的构想。","Tell us your location, intended use and preferred model. The more context you share, the more useful our first conversation can be.":"请说明项目地点、使用场景和意向产品。信息越具体，首次沟通就越有针对性。","CONTACT":"联系信息","Business email and messaging details will be added here.":"业务邮箱和即时通讯方式将于此处公布。","COMPANY":"所属企业","YOUTOME · A BFC China (百福中国) brand":"YOUTOME · 百福中国旗下品牌","PROJECT ENQUIRY":"项目咨询","Tell us about your plan.":"告诉我们您的计划。","Your name":"您的姓名","Email address":"电子邮箱","Country / region":"国家 / 地区","Interested in":"意向产品","Select a collection":"选择产品系列","Capsule House":"太空舱","Apple Cabin":"苹果舱","Expandable House":"拓展式房屋","Not sure yet":"暂未确定","Tell us about your project":"介绍您的项目","Copy enquiry details":"复制咨询内容","Contact details are being connected. For now, copy your project details and save them for our team.":"联系渠道正在接入。您可先复制并保存项目需求，待渠道上线后发送给我们。",
  "DESIGNED AROUND YOUR VISION":"围绕您的构想而设计","A new perspective on":"重新定义","everyday space.":"日常空间。","Discuss this home":"讨论这款产品","THE COLLECTION":"所属系列","IDEAL FOR":"适用场景","CONFIGURATION":"产品配置","Discuss options with our team":"与团队讨论配置选项","Images are design visualizations. Final specifications, materials and availability are subject to confirmation.":"图片为设计概念效果图。最终规格、材料和供货情况以确认为准。","EXPLORE MORE":"继续探索","Other ways to":"以更多方式","feel at home.":"感受家的自在。","LET'S SHAPE YOUR SPACE":"共同塑造您的空间","Ready to explore the possibilities?":"准备好探索更多可能了吗？","← All homes":"← 全部产品","flexible residential and hospitality projects":"灵活的居住与旅宿项目","private retreats and guest accommodation":"私人度假与宾客住宿","resort stays and distinctive rentals":"度假旅宿与特色租赁项目",
  "Explore":"探索","Discover design-led capsule houses, cabins and expandable prefab homes by YOUTOME, a BFC China brand.":"探索百福中国旗下 YOUTOME 品牌的太空舱、模块化小屋与拓展式预制房屋。","Explore YOUTOME capsule houses, apple cabins and expandable prefab homes. Find the right modular home for hospitality, rentals or personal living.":"探索 YOUTOME 太空舱、苹果舱与拓展式房屋，为酒店、租赁或私人居住寻找合适方案。","Learn how YOUTOME combines design-led modular homes, modular design and project support for hospitality and personal living.":"了解 YOUTOME 如何将模块化建筑设计与项目支持结合。","Tell YOUTOME about your prefab home project. Ask about capsule houses, apple cabins, expandable homes, specifications and delivery.":"向 YOUTOME 介绍您的预制房屋项目，咨询产品系列、规格和交付事宜。","Main navigation":"主导航","Mobile navigation":"移动端导航","Open menu":"打开菜单","Scroll to collections":"前往产品系列","Filter homes":"筛选产品","Intended use, number of units, timeline or anything else we should know":"使用场景、所需数量、期望时间及其他要求","Where is your project?":"项目位于哪里？","YOUTOME home":"YOUTOME 首页","Contemporary prefab cabin beside a mountain lake at dusk":"暮色中位于山湖边的现代预制小屋","Capsule house with panoramic glazing":"采用全景玻璃的太空舱","Apple cabin in a green landscape":"绿地中的苹果舱","Modular cabin in a mountain setting":"山地中的模块化小屋","Contemporary prefab cabin in a natural setting":"自然环境中的现代预制小屋","Modern modular cabin in a lakeside landscape":"湖边的现代模块化小屋",
  "A BETTER START":"更好的开始","What helps us plan":"高效规划","your project.":"您的项目。","A few practical details make the first conversation more useful. You can share them now or prepare them before reaching out.":"几项实用信息可以让首次沟通更有针对性。您可现在提供，也可在联系前整理好。","Location & climate":"地点与气候","Where will the home go, and will it be used year-round or seasonally?":"房屋将落在哪个地点？计划全年使用还是季节性使用？","Use & quantity":"用途与数量","Is this for a resort, rental, business or private living? How many units are planned?":"用于度假区、租赁、商业还是私人居住？计划采购多少套？","Site readiness":"场地准备","Consider vehicle access, ground conditions, utilities and any local approvals.":"请考虑车辆通行、地基条件、公共设施接入和当地审批要求。","Timing & scope":"时间与配置","Share your target schedule and which finishes or fittings matter most.":"请告知期望时间，以及最重视的饰面和设备配置。","Final specifications, site requirements and delivery terms are confirmed in a written proposal for each project.":"最终规格、场地要求与交付条件将在各项目的书面方案中确认。"
};
for(const name of ['Capsule One','Capsule Panorama','Capsule Grand','Apple Studio','Apple Living','Expandable One']){
  const audience=name.startsWith('Capsule')?'resort stays and distinctive rentals':name.startsWith('Apple')?'private retreats and guest accommodation':'flexible residential and hospitality projects';
  zh[`${name} brings the YOUTOME approach to ${audience}. Its architectural form creates a memorable first impression, while a considered interior can be configured around your project needs.`]=`${name} 将 YOUTOME 的设计理念带入${zh[audience]}。鲜明的建筑外观令人一眼难忘，内部空间可根据项目需求进行规划。`;
  zh[`${name} | YOUTOME Prefab Homes`]=`${name} | YOUTOME 预制房屋`;
}
zh['YOUTOME | Prefab Homes for Extraordinary Places']='YOUTOME | 为不凡目的地打造预制房屋';
zh['Prefab Homes & Modular Cabins | YOUTOME']='预制房屋与模块化小屋 | YOUTOME';
zh['About YOUTOME | Design-led Prefab Living']='关于 YOUTOME | 设计驱动的预制空间';
zh['Contact YOUTOME | Plan Your Prefab Home']='联系 YOUTOME | 规划您的预制房屋项目';
export default zh;
